//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donatools_Eva3.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int id_donacion { get; set; }
        public string nomb_donacion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
        public System.DateTime fecha_limite { get; set; }
        public Nullable<int> publico { get; set; }
        public int tipo { get; set; }
        public int usuario_fk { get; set; }
    
        public virtual Tipo Tipo1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
